### ISSUE TITLE
[Bug] Docker E2E path broken: ui-governance-1.spec.ts imports apps/web sources not mounted in the e2e container

### ISSUE THREAD

**Issue by jnhu76** [jnhu76/exam#503]
Refs #498
Refs #445

## As-built characterization

`pnpm e2e:docker` (`scripts/e2e/run.sh` + `docker-compose.test.yml`) currently aborts before running any test:

```text
Error: Cannot find module '/app/apps/web/src/lib/statusMeta' imported from /app/apps/e2e/e2e/ui-governance-1.spec.ts
```

## Root cause

`apps/e2e/e2e/ui-governance-1.spec.ts` (introduced by 98da7f9b, #439 V1–V4 durable geometry gates) imports web-side authorities via relative paths:

```ts
import { statusMeta } from "../../web/src/lib/statusMeta";
import { statusLabelKey } from "../../web/src/lib/statusMetaUtils";
import ... from "../../web/src/i18n/index";
```

The Docker e2e container (`docker-compose.test.yml` → `e2e` service) mounts only `./apps/e2e`, `./packages`, and `./node_modules` — `apps/web` is not mounted, so `/app/apps/web/...` cannot resolve. The imports are intentional on the WSL/CI path (the spec header documents web-side edits affecting e2e as the drift alarm working); the Docker container topology was never updated to match.

## Why it went unnoticed

CI's E2E lane (`.github/workflows/ci.yml`) runs Playwright directly on the runner against a full checkout — it never exercises the Docker e2e container path. The breakage is therefore invisible to CI and only reproduces via `pnpm e2e:docker`.

## Evidence

- Master @9585aa9f: full `pnpm e2e:docker` aborts with the error above (after the workspace `pnpm build`, so `@exam/*/dist` artifacts are present — this is not the missing-build trap).
- Same run with the file excluded via a positional path regex (`^(?!.*ui-governance).*$`) proceeds into the suite.
- CI E2E (runner path) is green on the same tree.

## Candidate fixes (decision needed)

1. Mount `./apps/web:/app/apps/web:ro` in the e2e service — preserves the drift-alarm imports, at the cost of a wider host mount.
2. Repackage the consumed authorities (`statusMeta`, `statusMetaUtils`, i18n instance) as a workspace package the container already mounts (`./packages`), and import from there.

Out of scope for the compose-authority convergence PR (pre-existing, independently discovered); this issue is the focused follow-up.

## Acceptance criteria

- `pnpm e2e:docker` runs the full suite including ui-governance specs without module-resolution errors.
- A regression note ties the e2e container mount set to the spec import surface (whichever fix is chosen).
